project_id = "skgdyggrxjtcphctkdat"

[functions.creator-impersonate]
verify_jwt = false

[functions.sync-team-results]
verify_jwt = false

[functions.send-commission-approval]
verify_jwt = false

[functions.generate-chatbot-prompt]
verify_jwt = false

[functions.ai-training-bot]
verify_jwt = false

[functions.generate-training-plan]
verify_jwt = false

[functions.generate-ai-courses]
verify_jwt = false

[functions.dashboard-insights]
verify_jwt = false
