project_id = "skgdyggrxjtcphctkdat"

[functions.creator-impersonate]
verify_jwt = false

[functions.sync-team-results]
verify_jwt = false

[functions.send-commission-approval]
verify_jwt = false

[functions.generate-chatbot-prompt]
verify_jwt = false
